[package]
name = "viz-rs"
version = "0.1.0"
edition = "2024"
[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
panic = "abort"

[dependencies]
tokio =   { version = "1.43.0", features = ["full"] }
axum =  { version = "0.8.1", features = ["multipart","macros", "ws"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
chrono = { version = "0.4.39", features = ["serde"] }
uuid = { version = "1.13.1", features = ["serde", "v4"] }
tower-http = { version = "0.6.2", features = ["trace", "cors", "timeout"] }
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "2.0.11"
dotenvy = "0.15"
#rust-bert = "0.23"
image = "0.25.5"
tch = { version = "0.19.0", features = [ ] }
anyhow = "1.0.79"
http = "1.2.0"
qdrant-client = "1.13.0"

grammers-client="0.7.0"
log = "0.4.25"
simple_logger="5.0.0"