services:


  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3011" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - shared-net
    volumes:
      - ./images:/static/img


configs:
  qdrant_config:
    content: |
      log_level: INFO      

networks:
  shared-net:
    driver: bridge

